### ISSUE TITLE
Checking all the certs used in the answer-file

### ISSUE THREAD

**Issue by waldirio** [waldirio/sos_analyze#142]
```
# egrep -A 3 "server_cert:" /etc/foreman-installer/scenarios.d/satellite-answers.yaml
  server_cert: "/root/satellite_cert/satellite_cert.pem"
  server_key: "/root/satellite_cert/satellite_key.pem"
  server_cert_req:
  server_ca_cert: "/root/satellite_cert/ca_cert_bundle.pem"
```
